language: python3

install:
  - pip install -q -r requirements.txt
before_script:
  - touch .env
  - echo "DJANGO_SETTINGS_MODULE=cbs.settings" >> .env
  - echo "SECRET_KEY=foo" >> .env
  - python manage.py migrate --noinput
  - python manage.py collectstatic  --noinput
addons:
  - ssh_known_hosts: "${HOST_IP}"
script:
  - python manage.py test
before_deploy:
  - echo ${KEY} > /tmp/deploy_rsa 
  - chmod 600 /tmp/deploy_rsa
deploy:
  provider: script
  script: bash deploy/deploy.sh
  on:
    branch: master
