# Generated by Django 2.2.1 on 2019-10-26 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, verbose_name="Client's Name")),
                ('client_logo', models.ImageField(upload_to='clients', verbose_name="Client's Logo")),
            ],
        ),
        migrations.CreateModel(
            name='ProvidedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_image', models.ImageField(default='default.jpg', null=True, upload_to='services', verbose_name='Service Heading')),
                ('name_of_service', models.CharField(max_length=50, verbose_name='Name of Service')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='Project Name')),
                ('project_location', models.CharField(max_length=50, verbose_name='Site Address')),
                ('project_description', models.CharField(default='NONE', max_length=300, verbose_name='Project Description')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_project.Client')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery', verbose_name='Image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_project.Project')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_project.ProvidedService')),
            ],
        ),
    ]
