# Generated by Django 2.2.1 on 2019-10-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_service', models.CharField(max_length=50, verbose_name='Name of Service')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(default='NONE', max_length=300, verbose_name='Project Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ManyToManyField(to='our_project.Service'),
        ),
    ]
