# Generated by Django 2.2.1 on 2019-10-26 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('our_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery', verbose_name='Image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_project.Project')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_project.ProvidedService')),
            ],
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
