# Generated by Django 2.2.1 on 2019-12-27 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('our_project', '0002_auto_20191026_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_image', models.ImageField(default='default.jpg', null=True, upload_to='products', verbose_name='Product')),
                ('name_of_product', models.CharField(max_length=50, verbose_name='Name of Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManagementConsultantAndMaintainence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_image', models.ImageField(default='default.jpg', null=True, upload_to='services', verbose_name='Service Heading')),
                ('pmc_for', models.CharField(max_length=50, verbose_name='PMC for ')),
            ],
        ),
        migrations.RenameModel(
            old_name='ProvidedService',
            new_name='Service',
        ),
        migrations.RemoveField(
            model_name='mygalleryimage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='mygalleryimage',
            name='service',
        ),
        migrations.AddField(
            model_name='mygalleryimage',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Image_Type+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='mygalleryimage',
            name='image_description',
            field=models.CharField(blank=True, max_length=50, verbose_name='Image Description'),
        ),
        migrations.AddField(
            model_name='mygalleryimage',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
