# Generated by Django 2.2.1 on 2019-12-27 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('our_project', '0003_auto_20191227_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygalleryimage',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'our_project'), ('model', 'Products')), models.Q(('app_label', 'our_project'), ('model', 'Service')), models.Q(('app_label', 'our_project'), ('model', 'ProjectManagementConsultantAndMaintainence')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Image_Type+', to='contenttypes.ContentType'),
        ),
    ]
