# Generated by Django 2.2.1 on 2019-12-27 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('our_project', '0004_auto_20191227_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygalleryimage',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='our_project.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='mygalleryimage',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'our_project'), ('model', 'products')), models.Q(('app_label', 'our_project'), ('model', 'service')), models.Q(('app_label', 'our_project'), ('model', 'projectmanagementconsultantandmaintainence')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Image_Type+', to='contenttypes.ContentType'),
        ),
    ]
