# Generated by Django 3.0.6 on 2020-05-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('our_project', '0005_auto_20191227_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery', verbose_name='Image')),
                ('image_description', models.CharField(blank=True, max_length=50, verbose_name='Image Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='mygalleryimage',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='mygalleryimage',
            name='project',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='ProjectManagementConsultantAndMaintainence',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_location',
            new_name='project_address',
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='our_project.Client'),
        ),
        migrations.DeleteModel(
            name='MyGalleryImage',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='our_project.Project', verbose_name='Project'),
        ),
    ]
