# Generated by Django 2.2.1 on 2019-08-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20190814_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='welcome_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='brief_description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tag_line',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutusinfo',
            name='main_description',
            field=models.CharField(max_length=1000),
        ),
    ]
