# Generated by Django 2.2.1 on 2019-08-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_auto_20190814_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=13)),
                ('query', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='homepage',
            name='brief_description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
