# Generated by Django 2.2.1 on 2019-08-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_auto_20190814_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
