# Generated by Django 2.2.1 on 2019-08-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_contactus_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='date',
            new_name='query_date',
        ),
    ]
