# Generated by Django 2.2.1 on 2019-08-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_auto_20190814_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='query_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
