# Generated by Django 2.1.5 on 2019-08-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0009_auto_20190814_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusinfo',
            name='main_description',
        ),
        migrations.AddField(
            model_name='aboutusinfo',
            name='main_description_paragraph_1',
            field=models.CharField(default='', max_length=500, verbose_name='First About Us Paragraph '),
        ),
        migrations.AddField(
            model_name='aboutusinfo',
            name='main_description_paragraph_2',
            field=models.CharField(default='', max_length=500, verbose_name='Second About Us Paragraph '),
        ),
        migrations.AddField(
            model_name='aboutusinfo',
            name='main_description_paragraph_3',
            field=models.CharField(default='', max_length=500, verbose_name='Third About Us Paragraph '),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='brief_description',
            field=models.CharField(max_length=2000, verbose_name='Small Introduction'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='tag_line',
            field=models.CharField(max_length=100, verbose_name='Tagline '),
        ),
    ]
