# Generated by Django 2.1.5 on 2019-08-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0010_auto_20190815_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusinfo',
            name='main_description_paragraph_1',
            field=models.CharField(max_length=500, verbose_name='First About Us Paragraph '),
        ),
        migrations.AlterField(
            model_name='aboutusinfo',
            name='main_description_paragraph_2',
            field=models.CharField(max_length=500, verbose_name='Second About Us Paragraph '),
        ),
        migrations.AlterField(
            model_name='aboutusinfo',
            name='main_description_paragraph_3',
            field=models.CharField(max_length=500, verbose_name='Third About Us Paragraph '),
        ),
    ]
