# Generated by Django 2.2.1 on 2019-08-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0011_auto_20190815_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=50, verbose_name='Name')),
                ('staff_designation', models.CharField(max_length=50, verbose_name='Designation')),
                ('staff_picture', models.ImageField(upload_to='staff', verbose_name='Photo ')),
            ],
        ),
    ]
