# Generated by Django 2.2.1 on 2019-08-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0012_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusinfo',
            name='main_description_paragraph_3',
            field=models.CharField(max_length=1000, verbose_name='Third About Us Paragraph '),
        ),
    ]
