# Generated by Django 2.2.1 on 2019-08-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0013_auto_20190815_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Slide Show Image', 'verbose_name_plural': 'Slide Show Images'},
        ),
    ]
