# Generated by Django 2.2.1 on 2019-08-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0014_auto_20190815_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusinfo',
            name='main_description_paragraph_1',
            field=models.TextField(max_length=500, verbose_name='First About Us Paragraph '),
        ),
        migrations.AlterField(
            model_name='aboutusinfo',
            name='main_description_paragraph_2',
            field=models.TextField(max_length=500, verbose_name='Second About Us Paragraph '),
        ),
        migrations.AlterField(
            model_name='aboutusinfo',
            name='main_description_paragraph_3',
            field=models.TextField(max_length=1000, verbose_name='Third About Us Paragraph '),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='query',
            field=models.TextField(verbose_name='Query'),
        ),
    ]
