# Generated by Django 2.2.1 on 2019-08-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0015_auto_20190815_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUsCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_header', models.CharField(max_length=15, verbose_name='Why Us Card Header')),
                ('card_body', models.CharField(max_length=50, verbose_name='Why Us Card Body')),
            ],
        ),
    ]
