# Generated by Django 2.2.1 on 2019-08-16 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0016_whyuscard'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyuscard',
            name='card',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='information.AboutUsInfo', verbose_name='Why Us'),
        ),
    ]
