# Generated by Django 2.2.1 on 2019-08-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0018_auto_20190816_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whyuscard',
            name='card_body',
            field=models.CharField(max_length=250, verbose_name='Why Us Card Body'),
        ),
    ]
