# Generated by Django 2.2.1 on 2019-08-16 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0019_auto_20190816_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whyuscard',
            options={'ordering': ('id',)},
        ),
    ]
