# Generated by Django 2.2.1 on 2019-10-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0021_staff_staff_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='organisation',
            field=models.CharField(default='NONE', max_length=50),
        ),
    ]
