# Generated by Django 2.2.1 on 2019-10-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0022_contactus_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='organisation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='query',
            field=models.TextField(verbose_name='Comments'),
        ),
    ]
