# Generated by Django 2.2.1 on 2019-10-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0023_auto_20191026_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_line', models.CharField(max_length=100, verbose_name='Tagline ')),
                ('brief_description', models.CharField(max_length=2000, verbose_name='Small Introduction')),
                ('about_card_1_title', models.CharField(max_length=50, verbose_name='About Us 1 Title')),
                ('about_card_1_description', models.CharField(max_length=200, verbose_name='About Us 1 Description')),
                ('about_card_1_image', models.ImageField(upload_to='homepage', verbose_name='About Us 1 Image ')),
                ('about_card_2_title', models.CharField(max_length=50, verbose_name='About Us 2 Title')),
                ('about_card_2_description', models.CharField(max_length=200, verbose_name='About Us 2 Description')),
                ('about_card_2_image', models.ImageField(upload_to='homepage', verbose_name='About Us 2 Image ')),
                ('about_card_3_title', models.CharField(max_length=50, verbose_name='About Us 3 Title')),
                ('about_card_3_description', models.CharField(max_length=200, verbose_name='About Us 3 Description')),
                ('about_card_3_image', models.ImageField(upload_to='homepage', verbose_name='About Us 3 Image ')),
            ],
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
