# Generated by Django 2.2.1 on 2019-10-28 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0024_auto_20191028_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_title', models.CharField(default='', max_length=10, verbose_name='Count Title')),
                ('count_value', models.IntegerField(default=0, verbose_name='Count Value')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.HomePageInformation')),
            ],
        ),
    ]
