# Generated by Django 2.2.1 on 2020-05-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0025_factcounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factcounter',
            name='home_page',
        ),
        migrations.RemoveField(
            model_name='whyuscard',
            name='card',
        ),
        migrations.DeleteModel(
            name='AboutUsInfo',
        ),
        migrations.DeleteModel(
            name='HomePageInformation',
        ),
    ]
