# Generated by Django 3.0.6 on 2020-05-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0026_auto_20200510_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FactCounter',
        ),
        migrations.DeleteModel(
            name='WhyUsCard',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='organisation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
